- src/Countdown.ts
- src/Event.ts
- src/app.ts
> (#1) Implement Countdown.appendTo

- Makefile
- package-lock.json
- package.json
- src/Countdown.ts
- src/app.ts
> (#10) Show time in a guessed user timezone

- Makefile
- README.md
- css/reset.css
- html/index.html
- less/main.less
- package-lock.json
- package.json
- ts/Countdown.ts
- ts/Event.ts
> (#6) Basic style

- html/index.html
> (#20) Fork me on github ribbon

- .gitignore
- scss/main.scss
- ts/CurrentEvent.ts
- ts/Event.ts
- ts/EventsForCurrentPeriod.ts
- ts/EventsForDay.ts
- ts/FutureEvent.ts
- ts/PastEvent.ts
- ts/Project.ts
- ts/app.ts
- ts/dto.ts
> (#25) Link event titles to corresponding projects instead of Twitch channel

- Makefile
- README.md
- scss/main.scss
- ts/CurrentEvent.ts
- ts/EventsForCurrentPeriod.ts
- ts/EventsForDay.ts
- ts/FutureEvent.ts
- ts/PastEvent.ts
- ts/app.ts
- ts/dto.ts
> (#41) Implement extra events mechanism

- html/index.html
- scss/main.scss
- ts/CancelledEvent.ts
- ts/Event.ts
- ts/EventsForDay.ts
- ts/app.ts
- ts/dto.ts
> (#23) Implement Cancelled Events

- ts/Event.ts
> (#37) Fix early activated event

- ts/CancelledEvent.ts
- ts/ConcatLists.ts
- ts/Countdown.ts
- ts/CurrentEvent.ts
- ts/Event.ts
- ts/EventsForCurrentPeriod.ts
- ts/EventsForDay.ts
- ts/FutureEvent.ts
- ts/List.ts
- ts/PastEvent.ts
- ts/UiComponent.ts
> (#51) Show no more than 2 past events

- ts/FailedScheduleLoad.ts
- ts/StateFromUrl.ts
- ts/app.ts
> (#42) Load state from a url

- ts/StateFromUrl.ts
> (#56) Implement StateFromUrl

- ts/FutureEvent.ts
- ts/PastEvent.ts
> (#66) Reimplement PastEvents using HTML components

- ts/EventsForDay.ts
- ts/dto.ts
> (#40) optional boundaries for recurring events

- ts/CurrentEvent.ts
- ts/Empty.ts
> (#63) Reimplement CurrentEvent with HTML components

- ts/FutureEvent.ts
- ts/PastEvent.ts
> (#78) Interpolate ids properly

- ts/CancelledEvent.ts
> (#62) Reimplement CancelledEvent with HTML components

- ts/CancelledEvent.ts
- ts/ComponentsArray.ts
- ts/ComponentsList.ts
- ts/CurrentEvent.ts
- ts/EventsForCurrentPeriod.ts
- ts/FilteredList.ts
- ts/FutureEvent.ts
- ts/ListOfNumbersRange.ts
- ts/MappedList.ts
- ts/PastEvent.ts
- ts/SlicedList.ts
> (#64) Reimplement EventsForCurrentPeriod with HTML components

- ts/EventsForDay.ts
- ts/dto/EventPatch.ts
- ts/dto/PatchedEvent.ts
- ts/dto/State.ts
- ts/dto/index.ts
> (#83) Patching events

- json/schedule.json
- scss/main.scss
- ts/CancelledEvent.ts
- ts/Countdown.ts
- ts/CurrentEvent.ts
- ts/EventsForDay.ts
- ts/FutureEvent.ts
- ts/PastEvent.ts
- ts/dto/Event.ts
- ts/dto/ExtraEvent.ts
- ts/dto/PatchedEvent.ts
- ts/dto/Project.ts
> (#90) Customizable channels for events

- default.nix
- package-lock.json
- package.json
- ts/DayOff.ts
- ts/Event.ts
- ts/EventsForCurrentPeriod.ts
- ts/EventsForDay.ts
>  (#96) Turn EventsForDay into DayOff when there are no events for day

- package-lock.json
- package.json
- ts/CancelledEvent.ts
- ts/CurrentEvent.ts
- ts/FutureEvent.ts
- ts/PastEvent.ts
- ts/html/Markdown.ts
- ts/html/index.ts
> (#14) Enable support for Markdown in Event's description

- ts/Event.ts
> (#102) Make an Event reactivate its own anchor

- scss/main.scss
- ts/CurrentEvent.ts
- ts/TwitchPlayer.ts
> (#73) Introduce TwitchPlayer into CurrentEvent

- Makefile
> Add sourcemaps

- Makefile
- html/index.html
- package-lock.json
- package.json
- scss/main.scss
- ts/app.ts
> add fontawesome via npm

- ts/TwitchPlayer.ts
> Add required url parameter for the player

- json/schedule.json
> Update description for Something

- json/schedule.json
- ts/CancelledEvent.ts
- ts/CurrentEvent.ts
- ts/FutureEvent.ts
- ts/PastEvent.ts
> (#116) Replace channel URL with name
